# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
